### PR TITLE
Branch Brave dev, with structure of _printf.c, _printchar.c and some quick tests

### PR DESCRIPTION
**Pull request by bravemaster3**
Here, I added the structure of the main file.
Before changing anything to the structure, let's discuss it because there may be a reason why I did something a certain way, even if it doesn't seem important.
What this commit contains:

 _printf.c: the main structure
_printchar.c: prints characters without specifier.
test folder: contains some quick tests. Just copy paste the test in programmiz to see. We will replace these by real tests later. For now, it gives you an idea how it works.

### CODE REVIEW

**Comment by Paphra** [comment]
Okay, this good, though am not sure why you had to declare your own _printchar.c file with a _putchar functionn which am to work on ...

**Comment by Paphra** [comment]
Also, whenever we are doing something, we to always be getting from the main, merging to our branches and start from their, always checking on the structures of others such that we do not conflict

**Review by Paphra — APPROVED** [review]
We need to always first check on what the other person has done such that we do not conflict each other

**Comment by bravemaster3** [comment]
Noted.
Sorry for not updating - merging  from main before editing the second time.

**Pull request merged**
